export { default as Header } from './Header'
export { default as Footer } from './Footer'
export { default as Hero } from './Hero'
export { default as About } from './About'
export { default as Contact } from './Contact'
export { default as Section } from './Section'
export { default as ProjectCard } from './ProjectCard'
